<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class OptionsQuestions extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            ['questions_id' => 1, 'options_id' => 1],
            ['questions_id' => 1, 'options_id' => 2],
            ['questions_id' => 1, 'options_id' => 3],
            ['questions_id' => 1, 'options_id' => 4],
            ['questions_id' => 2, 'options_id' => 1],
            ['questions_id' => 2, 'options_id' => 2],
            ['questions_id' => 2, 'options_id' => 3],
            ['questions_id' => 2, 'options_id' => 4],
            [ 'questions_id' => 3, 'options_id' => 1 ],
            [ 'questions_id' => 3, 'options_id' => 2 ],
            [ 'questions_id' => 3, 'options_id' => 3 ],
            [ 'questions_id' => 3, 'options_id' => 4 ],
            [ 'questions_id' => 4, 'options_id' => 1 ],
            [ 'questions_id' => 4, 'options_id' => 2 ],
            [ 'questions_id' => 4, 'options_id' => 3 ],
            [ 'questions_id' => 4, 'options_id' => 4 ],
            [ 'questions_id' => 5, 'options_id' => 1 ],
            [ 'questions_id' => 5, 'options_id' => 2 ],
            [ 'questions_id' => 5, 'options_id' => 3 ],
            [ 'questions_id' => 5, 'options_id' => 4 ],
            [ 'questions_id' => 6, 'options_id' => 1 ],
            [ 'questions_id' => 6, 'options_id' => 2 ],
            [ 'questions_id' => 6, 'options_id' => 3 ],
            [ 'questions_id' => 6, 'options_id' => 4 ],
            [ 'questions_id' => 7, 'options_id' => 1 ],
            [ 'questions_id' => 7, 'options_id' => 2 ],
            [ 'questions_id' => 7, 'options_id' => 3 ],
            [ 'questions_id' => 7, 'options_id' => 4 ],
            [ 'questions_id' => 8, 'options_id' => 1 ],
            [ 'questions_id' => 8, 'options_id' => 2 ],
            [ 'questions_id' => 8, 'options_id' => 3 ],
            [ 'questions_id' => 8, 'options_id' => 4 ],
            [ 'questions_id' => 9, 'options_id' => 1 ],
            [ 'questions_id' => 9, 'options_id' => 2 ],
            [ 'questions_id' => 9, 'options_id' => 3 ],
            [ 'questions_id' => 9, 'options_id' => 4 ],
            [ 'questions_id' => 10, 'options_id' => 1 ],
            [ 'questions_id' => 10, 'options_id' => 2 ],
            [ 'questions_id' => 10, 'options_id' => 3 ],
            [ 'questions_id' => 10, 'options_id' => 4 ],
            [ 'questions_id' => 11, 'options_id' => 1 ],
            [ 'questions_id' => 11, 'options_id' => 2 ],
            [ 'questions_id' => 11, 'options_id' => 3 ],
            [ 'questions_id' => 11, 'options_id' => 4 ],
            [ 'questions_id' => 12, 'options_id' => 1 ],
            [ 'questions_id' => 12, 'options_id' => 2 ],
            [ 'questions_id' => 12, 'options_id' => 3 ],
            [ 'questions_id' => 12, 'options_id' => 4 ],
            [ 'questions_id' => 13, 'options_id' => 1 ],
            [ 'questions_id' => 13, 'options_id' => 2 ],
            [ 'questions_id' => 13, 'options_id' => 3 ],
            [ 'questions_id' => 13, 'options_id' => 4 ],
            [ 'questions_id' => 14, 'options_id' => 1 ],
            [ 'questions_id' => 14, 'options_id' => 2 ],
            [ 'questions_id' => 14, 'options_id' => 3 ],
            [ 'questions_id' => 14, 'options_id' => 4 ],
            [ 'questions_id' => 15, 'options_id' => 1 ],
            [ 'questions_id' => 15, 'options_id' => 2 ],
            [ 'questions_id' => 15, 'options_id' => 3 ],
            [ 'questions_id' => 15, 'options_id' => 4 ],
            [ 'questions_id' => 16, 'options_id' => 1 ],
            [ 'questions_id' => 16, 'options_id' => 2 ],
            [ 'questions_id' => 16, 'options_id' => 3 ],
            [ 'questions_id' => 16, 'options_id' => 4 ],
            [ 'questions_id' => 17, 'options_id' => 1 ],
            [ 'questions_id' => 17, 'options_id' => 2 ],
            [ 'questions_id' => 17, 'options_id' => 3 ],
            [ 'questions_id' => 17, 'options_id' => 4 ],
            [ 'questions_id' => 18, 'options_id' => 1 ],
            [ 'questions_id' => 18, 'options_id' => 2 ],
            [ 'questions_id' => 18, 'options_id' => 3 ],
            [ 'questions_id' => 18, 'options_id' => 4 ],
            [ 'questions_id' => 19, 'options_id' => 1 ],
            [ 'questions_id' => 19, 'options_id' => 2 ],
            [ 'questions_id' => 19, 'options_id' => 3 ],
            [ 'questions_id' => 19, 'options_id' => 4 ],
            [ 'questions_id' => 20, 'options_id' => 1 ],
            [ 'questions_id' => 20, 'options_id' => 2 ],
            [ 'questions_id' => 20, 'options_id' => 3 ],
            [ 'questions_id' => 20, 'options_id' => 4 ],
            [ 'questions_id' => 21, 'options_id' => 1 ],
            [ 'questions_id' => 21, 'options_id' => 2 ],
            [ 'questions_id' => 21, 'options_id' => 3 ],
            [ 'questions_id' => 21, 'options_id' => 4 ],
            [ 'questions_id' => 22, 'options_id' => 1 ],
            [ 'questions_id' => 22, 'options_id' => 2 ],
            [ 'questions_id' => 22, 'options_id' => 3 ],
            [ 'questions_id' => 22, 'options_id' => 4 ],
            [ 'questions_id' => 23, 'options_id' => 1 ],
            [ 'questions_id' => 23, 'options_id' => 2 ],
            [ 'questions_id' => 23, 'options_id' => 3 ],
            [ 'questions_id' => 23, 'options_id' => 4 ],
            [ 'questions_id' => 24, 'options_id' => 1 ],
            [ 'questions_id' => 24, 'options_id' => 2 ],
            [ 'questions_id' => 24, 'options_id' => 3 ],
            [ 'questions_id' => 24, 'options_id' => 4 ],
            [ 'questions_id' => 25, 'options_id' => 1 ],
            [ 'questions_id' => 25, 'options_id' => 2 ],
            [ 'questions_id' => 25, 'options_id' => 3 ],
            [ 'questions_id' => 25, 'options_id' => 4 ],
            [ 'questions_id' => 26, 'options_id' => 1 ],
            [ 'questions_id' => 26, 'options_id' => 2 ],
            [ 'questions_id' => 26, 'options_id' => 3 ],
            [ 'questions_id' => 26, 'options_id' => 4 ],
            [ 'questions_id' => 27, 'options_id' => 10 ],
            [ 'questions_id' => 27, 'options_id' => 11 ],
            [ 'questions_id' => 27, 'options_id' => 12 ],
            [ 'questions_id' => 27, 'options_id' => 13 ],
            [ 'questions_id' => 28, 'options_id' => 14 ],
            [ 'questions_id' => 28, 'options_id' => 15 ],
            [ 'questions_id' => 28, 'options_id' => 16 ],
            [ 'questions_id' => 28, 'options_id' => 17 ],
            [ 'questions_id' => 29, 'options_id' => 18 ],
            [ 'questions_id' => 29, 'options_id' => 19 ],
            [ 'questions_id' => 29, 'options_id' => 20 ],
            [ 'questions_id' => 29, 'options_id' => 21 ],
            [ 'questions_id' => 30, 'options_id' => 22 ],
            [ 'questions_id' => 30, 'options_id' => 23 ],
            [ 'questions_id' => 30, 'options_id' => 24 ],
            [ 'questions_id' => 30, 'options_id' => 25 ],
            [ 'questions_id' => 31, 'options_id' => 1 ],
            [ 'questions_id' => 31, 'options_id' => 27 ],
            [ 'questions_id' => 31, 'options_id' => 28 ],
            [ 'questions_id' => 31, 'options_id' => 29 ],
            [ 'questions_id' => 32, 'options_id' => 26 ],
            [ 'questions_id' => 32, 'options_id' => 27 ],
            [ 'questions_id' => 32, 'options_id' => 28 ],
            [ 'questions_id' => 32, 'options_id' => 29 ],
            [ 'questions_id' => 33, 'options_id' => 26 ],
            [ 'questions_id' => 33, 'options_id' => 27 ],
            [ 'questions_id' => 33, 'options_id' => 28 ],
            [ 'questions_id' => 33, 'options_id' => 29 ],
            [ 'questions_id' => 34, 'options_id' => 30 ],
            [ 'questions_id' => 34, 'options_id' => 31 ],
            [ 'questions_id' => 34, 'options_id' => 32 ],
            [ 'questions_id' => 34, 'options_id' => 33 ],
            [ 'questions_id' => 35, 'options_id' => 26 ],
            [ 'questions_id' => 35, 'options_id' => 27 ],
            [ 'questions_id' => 35, 'options_id' => 28 ],
            [ 'questions_id' => 35, 'options_id' => 29 ],
            [ 'questions_id' => 36, 'options_id' => 34 ],
            [ 'questions_id' => 36, 'options_id' => 35 ],
            [ 'questions_id' => 36, 'options_id' => 36 ],
            [ 'questions_id' => 36, 'options_id' => 37 ],
            [ 'questions_id' => 37, 'options_id' => 38 ],
            [ 'questions_id' => 37, 'options_id' => 39 ],
            [ 'questions_id' => 37, 'options_id' => 40 ],
            [ 'questions_id' => 37, 'options_id' => 41 ],
            [ 'questions_id' => 38, 'options_id' => 26 ],
            [ 'questions_id' => 38, 'options_id' => 27 ],
            [ 'questions_id' => 38, 'options_id' => 28 ],
            [ 'questions_id' => 38, 'options_id' => 42 ],
            [ 'questions_id' => 39, 'options_id' => 43 ],
            [ 'questions_id' => 39, 'options_id' => 44 ],
            [ 'questions_id' => 39, 'options_id' => 45 ],
            [ 'questions_id' => 39, 'options_id' => 46 ],
            [ 'questions_id' => 40, 'options_id' => 47 ],
            [ 'questions_id' => 40, 'options_id' => 48 ],
            [ 'questions_id' => 40, 'options_id' => 49 ],
        ];
        DB::table('options_questions')->insert($data);
    }
}
